config/routes.rb
Anytimemoney::Application.routes.draw do  
  get "signup" => "users#new" , :as => "signup"
  match '/signup', to: 'users#create', via: :post
  match '/users/create' , to: 'users#create' ,via: :post
  get 'pin_check' => "users#create" ,:as => "pin_check"
  get "find_accnum" => "users#edit", :as => "find_accnum" 
  match "withdraw_money" => "users#withdraw_money", :as => "withdraw_money" , via: [:post]
  match "deposite_money" => "users#deposite_money" , :as => "deposite_money" , via: [:post]  
  get "home" => "users#home" , :as => "home"   
  get "withdrw_err" => "users#withdrw_err" ,:as => "withdrw_err"
  get "withdrw_succ" => "users#withdrw_succ" ,:as => "withdrw_succ"
  get "deposite_succ" => "users#deposite_succ" , :as => "deposite_succ"
  get "logout" => "users#destroy" , :as => "logout"
  get "show" => "users#show" , :as => "show"
  resources :users do
    collection do
      
      get 'home'
      get 'withdrw_succ'
      get 'deposite_succ'
      
      get 'withdrw_err'
      post 'deposite_money'
      
      post 'withdraw_money'
    end
  end
  root:to => 'users#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # attr_accessor :account, :name, :balance ,:pin

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    logger.info "Index User info"
    Rails.logger.info "sample text"
  @user=User.find(:first, :conditions=>["account = ?", params[:account]])
  end
  
  
  def new 
    logger.info "Index the userdetails"
    @user=User.new(user_params)
  end
  
  
  def create
    
    if(params.has_key?(:account) && params.has_key?(:balance) && params.has_key?(:name) && params.has_key?(:pin))
      @user=User.new(user_params)
      if @user.save
         redirect_to root_url
       else
         render "new"
       end
    elsif params.has_key?(:account)
     @user=User.find(:first, :conditions=>["account = ?", params[:account]])
     if @user.nil?
        redirect_to signup_path
        elsif @user.account==params[:account].to_i
          redirect_to pin_check_path
        else
          redirect_to signup_path
        end
    elsif params.has_key?(:pin)
      @user=User.find(:first, :conditions=>["pin = ?", params[:pin]])
      if @user.nil?
        redirect_to signup_path
        elsif @user.pin==params[:pin].to_i
          session[:user_id] = @user.id
          redirect_to home_path
         else
           redirect_to pin_check_path
        end
      end 
 end
  
  def edit
    @user=User.new
  end
  
  def show
     @user = User.find(session[:user_id])
   puts session[:user_id]
  end
  
  
  
  
  
  def home
    @user = User.find(session[:user_id])
  end
  
  
  
  
  def withdraw_money
    @user=User.find(session[:user_id])
   
    if params[:balance].to_f > @user.balance
    
      redirect_to withdrw_err_path
     else
       
      @user.balance=@user.balance - params[:balance].to_f
      @user.update_attribute(:balance, @user.balance)
    
    redirect_to withdrw_succ_path
    end
  end
  
  def withdrw_err
     @user=User.find(session[:user_id])
  end
  
  def withdrw_succ
    @user=User.find(session[:user_id])
  end
  def deposite_succ
    @user=User.find(session[:user_id])
  end
  def deposite_money
    @user=User.find(session[:user_id])
    @user.balance=@user.balance + params[:balance].to_f
      @user.update_attribute(:balance, @user.balance)
    
    redirect_to deposite_succ_path
  end
  def destroy
    session[:user_id] = nil
    puts session[:user_id]
    redirect_to root_url
  end
  
  def user_params
    allow = [:name, :account, :pin, :balance]
    params.permit(allow)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Anytimemoney</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="http://railsgirls.com/assets/bootstrap.css">

</head>
<body class="body" >

<%= yield %>

</body>
</html>

app/views/users/create.html.erb
<h1 >LookUp Pin</h1>

<%= form_tag('/users/create')  do   %>
<p>
	
	    Pin Number 		<%= password_field_tag 'pin'%>
    
</p>
 <p class="button"><%= submit_tag "CheckPin" %></p>
<% end %>

app/views/users/deposite_succ.html.erb
<p>  You have successfully depoaited money </p><br />
Your transaction successfully completed ....  <br />
Your Balance is <%= @user.balance %> <br />
<%= link_to "Back", home_path, :class => "dropdown-toggle", :data => {:toggle=>"dropdown"} %><br /><br /><br />
</p> 

app/views/users/edit.html.erb
<h1 >LookUp Account</h1>

<%= form_tag('/users/lookup_acnum')  do   %>
<p>
	Account Number 	<%= text_field_tag 'account' %><br />
	    Pin Number 		<%= password_field_tag 'pin'%>
    
</p>
 <p class="button"><%= submit_tag "LookUpAccount" %></p>
<% end %>
<%= link_to "Back", root_url, :class => "dropdown-toggle", :data => {:toggle=>"dropdown"} %><br />

app/views/users/home.html.erb
<h1>X Y Z Bank Pvt Ltd</h1>
<table border="1">
	<tr>
		<th>Account Number</th>
		<th>Name</th>
		<th>Current Balance</th>
	</tr>
	<tr>
		<td><%= @user.account %></td>
		<td><%= @user.name %></td>
		<td><%= @user.balance %></td>
	</tr>
</table>
<%= form_tag('users/withdraw_money')  do   %>
<h3 >Withdraw Money</h3>
<p>
	Enter Emount  <%= text_field_tag 'balance' %><br />
    
</p>
 <p class="button"><%= submit_tag "WithDraw" %></p>
<% end %>
<%= form_tag('users/deposite_money')  do   %>
<h3>Deposite  Money</h3>
<p>
	Enter Emount  <%= text_field_tag 'balance' %><br />
    
</p>
 <p class="button"><%= submit_tag "Deposite" %></p>
<% end %>
<!-- <%= link_to "Show Balance", show_path, :class => "dropdown-toggle", :data => {:toggle=>"dropdown"} %><br /><br /><br /> -->
<%= link_to "Log Out", logout_path, :class => "dropdown-toggle", :data => {:toggle=>"dropdown"} %><br /><br /><br />

app/views/users/index.html.erb
<h1> Welcome to X Y Z Bank Pvt Ltd</h1>
<%= link_to "SignUp", signup_path, :class => "dropdown-toggle", :data => {:toggle=>"dropdown"} %><br />

<%= form_tag('/users/create')  do   %>
<p>
	Account Number 	<%= text_field_tag 'account' %><br />
	
    
</p>
 <p class="button"><%= submit_tag "LookUpAccount" %></p>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for('/users/create') do  %>
  
  <p>
	Name <br />
    <%= text_field_tag 'name' %>
</p>
<p>
	Account<br />
    <%= text_field_tag 'account' %>
</p>
<p>
	Balance<br />
    <%= text_field_tag 'balance' %>
</p>
<p>
    Pin <br />
    <%= password_field_tag 'pin'%>
  </p>
 <p class="button"><%= submit_tag "SignUp" %></p>
<% end %>

<%= link_to "Back", root_url, :class => "dropdown-toggle", :data => {:toggle=>"dropdown"} %>

app/views/users/show.html.erb
Name <%= @user.name%><br />
Account <%= @user.account%><br />
Your Balance is   <%= @user.balance %> <br /><br />
<%= link_to "Back", home_path, :class => "dropdown-toggle", :data => {:toggle=>"dropdown"} %><br /><br /><br />

app/views/users/withdrw_err.html.erb
You do not have sufficient balance in your account  <br />
Your Balance is <%= @user.balance%>
<%= link_to "Tryagain", home_path, :class => "dropdown-toggle", :data => {:toggle=>"dropdown"} %><br /><br /><br />

app/views/users/withdrw_succ.html.erb
<p>Take your money <br />
Your transaction successfully completed ....  <br />
Your Balance is <%= @user.balance %> <br />
<%= link_to "Back", home_path, :class => "dropdown-toggle", :data => {:toggle=>"dropdown"} %><br /><br /><br />
</p> 